name: Check formatting

on:
  push:
    # The CI is executed on every push on every branch
    branches:
      - main
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - main

  schedule:
    # The CI is executed every day at 8am
    - cron: "0 8 * * *"

jobs:
  check-code:
    runs-on: ghcr.io/scientificcomputing/fenics-gmsh:2023-04-21

    steps:
      # This action sets the current path to the root of your github repo
      - uses: actions/checkout@v3

      - name: Install code
        run: python -m pip install .[dev]

      - name: Flake8 code
        run: python -m flake8 -v

      - name: Mypy check
        run: python -m mypy -v
